<template>
  <div class="page-card"><div class="page-hero"><div><div class="section-eyebrow">Quiz Editor</div><h1 class="page-title">{{ form.quizId ? '编辑测验' : '新建测验' }}</h1><p class="page-subtitle">题目设计面向课堂活动，支持单选题与填空题。</p></div><el-button @click="$router.push('/teacher/quiz')">返回测验列表</el-button></div>
  <el-form :model="form" label-position="top"><div class="form-grid"><el-form-item label="所属课堂"><el-select v-model="form.sessionId" filterable><el-option v-for="item in sessions" :key="item.id" :label="`${item.sessionTitle} · ${courseName(item.courseId)}`" :value="item.id" /></el-select></el-form-item><el-form-item label="测验标题"><el-input v-model="form.quizTitle" /></el-form-item><el-form-item label="开始时间"><el-date-picker v-model="form.startTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item><el-form-item label="结束时间"><el-date-picker v-model="form.endTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item></div><el-form-item label="测验说明"><el-input v-model="form.quizDesc" type="textarea" :rows="4" /></el-form-item>
  <section class="surface-card" style="margin-top: 16px;"><div class="action-row" style="justify-content: space-between;"><h3 class="surface-card__title">题目列表</h3><el-button type="primary" plain @click="addQuestion">新增题目</el-button></div><div v-for="(item, index) in form.questions" :key="index" class="timeline-item" style="margin-top: 14px;"><div class="form-grid"><el-form-item :label="`题目 ${index + 1}`"><el-input v-model="item.questionTitle" type="textarea" :rows="3" /></el-form-item><el-form-item label="题型"><el-select v-model="item.questionType"><el-option label="单选题" value="SINGLE" /><el-option label="填空题" value="FILL" /></el-select></el-form-item><el-form-item label="答案"><el-input v-model="item.correctAnswer" /></el-form-item><el-form-item label="分值"><el-input-number v-model="item.score" :min="1" :max="100" /></el-form-item></div><el-form-item v-if="item.questionType === 'SINGLE'" label="选项 JSON"><el-input v-model="item.optionsJson" /></el-form-item><div class="action-row"><el-button size="small" type="danger" plain @click="removeQuestion(index)">删除题目</el-button></div></div></section>
  <div class="action-row" style="margin-top: 18px;"><el-button type="primary" :loading="saving" @click="submit">保存测验</el-button></div></el-form></div>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { api } from '../../api'
const route = useRoute(); const router = useRouter(); const saving = ref(false); const sessions = ref([]); const courses = ref([])
const form = reactive({ quizId: route.query.quizId ? Number(route.query.quizId) : null, courseId: route.query.courseId ? Number(route.query.courseId) : undefined, sessionId: route.query.sessionId ? Number(route.query.sessionId) : undefined, quizTitle: '', quizDesc: '', startTime: '', endTime: '', questions: [] })
const courseMap = computed(() => Object.fromEntries(courses.value.map((item) => [item.id, item.courseName]))); const courseName = (id) => courseMap.value[id] || `课程 ${id}`
const loadBase = async () => { const [courseRes, sessionRes] = await Promise.all([api.teacherCourses({ pageNum: 1, pageSize: 100 }), api.teacherSessions({})]); courses.value = courseRes.records || []; sessions.value = sessionRes || [] }
const loadDetail = async () => { if (!form.quizId) { addQuestion(); return } const quizList = await api.teacherQuizzes({ sessionId: form.sessionId }); const current = (quizList || []).find((item) => Number(item.id) === Number(form.quizId)); if (current) { form.quizTitle = current.quizTitle || ''; form.quizDesc = current.quizDesc || ''; form.startTime = current.startTime || ''; form.endTime = current.endTime || ''; form.sessionId = current.sessionId || form.sessionId; form.courseId = current.courseId || form.courseId } const questionList = await api.teacherQuizQuestions(form.quizId); form.questions = (questionList || []).map((item, index) => ({ questionTitle: item.questionTitle, questionType: item.questionType, optionsJson: item.optionsJson || '[]', correctAnswer: item.correctAnswer || '', score: item.score || 10, sortNo: index + 1 })); if (!form.questions.length) addQuestion() }
const addQuestion = () => form.questions.push({ questionTitle: '', questionType: 'SINGLE', optionsJson: '["A","B","C","D"]', correctAnswer: '', score: 10, sortNo: form.questions.length + 1 })
const removeQuestion = (index) => { form.questions.splice(index, 1) }
const submit = async () => { saving.value = true; try { const session = sessions.value.find((item) => Number(item.id) === Number(form.sessionId)); const payload = { sessionId: form.sessionId, courseId: session?.courseId || form.courseId, quizTitle: form.quizTitle, quizDesc: form.quizDesc, totalScore: form.questions.reduce((sum, item) => sum + Number(item.score || 0), 0), startTime: form.startTime, endTime: form.endTime, questions: form.questions.map((item, index) => ({ ...item, sortNo: index + 1 })) }; if (form.quizId) { await api.updateQuiz(form.quizId, payload); ElMessage.success('测验已更新') } else { await api.createQuiz(payload); ElMessage.success('测验已创建') } router.push('/teacher/quiz') } finally { saving.value = false } }
onMounted(async () => { await loadBase(); await loadDetail() })
</script>
